### ISSUE TITLE
Completion including method local vars which are out of scope

### ISSUE THREAD

**Issue by rohrlich** [goki/pi#5]
Local vars are being included in completion results, for example see screenshot,

![screen shot 2019-02-03 at 10 15 09 am](https://user-images.githubusercontent.com/22350787/52179869-b1a0d600-279c-11e9-9c18-f6bd2aa1cc5f.png)

**Comment by rcoreilly** [comment]
Yep go ahead and add a new set of methods.  FindNamePrefixRecursive vs. FindNamePrefix?

**Comment by rohrlich** [comment]
Yes, that naming is very clear!

**Comment by rohrlich** [comment]
Done
